package vueDM;

import java.util.ArrayList;

public interface DataDM {

	String[] choixAvantages = { "05 : Alliés Nv1", "10 : Alliés Nv2", "15 : Alliés Nv3", "20 : Alliés Nv4",
			"05 : Alphabétisation Nv1", "10 : Alphabétisation Nv2", "15 : Alphabétisation Nv3", "05 : Ambidextre",
			"10 : Bon sens", "05 : Bonne réputation Nv1", "10 : Bonne réputation Nv2", "15 : Bonne réputation Nv3",
			"20 : Bonne réputation Nv4", "15 : Chanceux Nv1", "30 : Chanceux Nv2", "60 : Chanceux Nv3",
			"05 : Charisme Nv1", "10 : Charisme Nv2", "15 : Charisme Nv3", "05 : Défense améliorée Nv1",
			"15 : Défense améliorée Nv2", "25 : Défense améliorée Nv3", "15 : Don de la magie Nv1",
			"25 : Don de la magie Nv2", "35 : Don de la magie Nv3", "02 : Don des langues Nv1",
			"04 : Don des langues Nv2", "06 : Don des langues Nv3", "08 : Don des langues Nv4", "15 : Empathie",
			"05 : Empathie animale", "05 : grade Militaire Nv1", "10 : grade Militaire Nv2", "15 : grade Militaire Nv3",
			"20 : grade Militaire Nv4", "25 : grade Militaire Nv5", "30 : grade Militaire Nv6",
			"35 : grade Militaire Nv7", "40 : grade Militaire Nv8", "05 : Contact faible", "10 : Contact moyen",
			"15 : Contact fort", "20 : Contact puissant", "05 : Guérison rapide", "15 : Guérison trés rapide",
			"02 : Intrépide Nv1", "04 : Intrépide Nv2", "06 : Intrépide Nv3", "08 : Intrépide Nv4",
			"05 : Membre des forces de l'Ordre Nv1", "10 : Membre des forces de l'Ordre Nv2",
			"15 : Membre des forces de l'Ordre Nv3", "01 : Musicien né Nv1", "02 : Musicien né Nv2",
			"03 : Musicien né Nv3", "04 : Musicien né Nv4", "05 : Musicien né Nv5", "01 : Nyctalope Nv1",
			"02 : Nyctalope Nv2", "03 : Nyctalope Nv3", "04 : Nyctalope Nv4", "05 : Nyctalope Nv5",
			"05 : Protecteur faible", "10 : Protecteur normale", "15 : Protecteur puissant", "05 : Ordination Nv1",
			"10 : Ordination Nv2", "15 : Ordination Nv3", "10 : Origine inhabituelle", "15 : réflexe aiguisé",
			"10 : résistance à la douleur", "02 : résistance à la magies Nv1", "04 : résistance à la magies Nv2",
			"06 : résistance à la magies Nv3", "08 : résistance à la magies Nv4", "10 : résistance à la magies Nv5",
			"05 : résistance aux poisons", "05 : résistance aux maladies Nv1", "10 : résistance aux maladies Nv2",
			"10 : Richesse Nv1", "20 : Richesse Nv2", "30 : Richesse Nv3", "40 : Richesse Nv4", "50 : Richesse Nv5",
			"10 : Robuste Nv1", "25 : Robuste Nv2", "02 : Sens aiguisés Nv1", "04 : Sens aiguisés Nv2",
			"06 : Sens aiguisés Nv3", "08 : Sens aiguisés Nv4", "10 : Sens aiguisés Nv5", "05 : Sens de l'orientation",
			"15 : Sens du danger", "05 : Souple", "05 : Statut Nv1", "10 : Statut Nv2", "15 : Statut Nv3",
			"20 : Statut Nv4", "25 : Statut Nv5", "15 : Téméraire", "05 : tenace", "05 : Vigilant Nv1",
			"10 : Vigilant Nv2", "15 : Vigilant Nv3", "10 : Voix", "04 : Volonté de fer Nv1", "08 : Volonté de fer Nv2",
			"12 : Volonté de fer Nv3", "16 : Volonté de fer Nv4", };

	String[] choixDesavantages = { "15 : Alcoolique Nv1", "25 : Alcoolique Nv1", "10 : Assoiffé de sang", "10 : Avare",
			"15 : Boiteux", "15 : Borgne", "05 : Code de l'honneur Nv1", "10 : Code de l'honneur Nv2",
			"15 : Code de l'honneur Nv3", "35 : Cul-de-jatte", "15 : Cupide", "05 : Curieux", "05 : Délirant Nv1",
			"10 : Délirant Nv2", "15 : Délirant Nv3", "05 : Dépendant Nv1", "10 : Dépendant Nv2", "15 : Dépendant Nv3",
			"20 : Dépendant Nv4", "10 : Dur d'oreille", "05 : Ennemie faible", "10 : Ennemie moyen",
			"15 : Ennemie fort", "30 : Ennemie puissant", "40 : Ennemie trés puissant...", "08 : Faible volonté Nv1",
			"16 : Faible volonté Nv2", "24 : Faible volonté Nv3", "02 : Fidéle Nv1", "05 : Fidéle Nv2",
			"10 : Fidéle Nv3", "15 : Fidéle Nv4", "20 : Fidéle Nv5", "05 : Franc", "05 : Goinfre", "05 : Gros Nv1",
			"10 : Gros Nv2", "20 : Gros Nv3", "10 : Honnête", "10 : Implusif", "05 : Infériorité sociale Nv1",
			"10 : Infériorité sociale Nv2", "15 : Infériorité sociale Nv3", "20 : Infériorité sociale Nv4",
			"10 : Irritable", "10 : Jaloux", "10 : Lâche", "05 : Maigre", "05 : Manie exaspérante Nv1",
			"10 : Manie exaspérante Nv2", "15 : Manie exaspérante Nv3", "10 : Malchanceux", "20 : Manchot",
			"05 : Mauvaise réputation Nv1", "10 : Mauvaise réputation Nv2", "15 : Mauvaise réputation Nv3",
			"20 : Mauvaise réputation Nv4", "25 : Mauvaise vue", "05 : Obsession Nv1", "10 : Obsession Nv2",
			"15 : Obsession Nv2", "15 : Pacifiste", "10 : Paresseux", "05 : Phobie Nv1", "10 : Phobie Nv2",
			"15 : Phobie Nv3", "05 : Présomptueux", "15 : Primitif", "05 : Protégé Nv1", "10 : Protégé Nv2",
			"15 : Protégé Nv3", "02 : Responsabilité Nv1", "05 : Responsabilité Nv2", "10 : Responsabilité Nv3",
			"15 : Responsabilité Nv4", "05 : Richesse Nv-1", "10 : Richesse Nv-2", "15 : Richesse Nv-3",
			"15 : Séducteur impénitent", "05 : Serment mineur", "10 : Serment important", "15 : Serment majeur",
			"05 : Statut Nv-1", "10 : Statut Nv-2", "15 : Statut Nv-3", "05 : Têtu", "10 : Tyrant", "25 : Unijambiste",

	};

	String choixCompetences[] = { "01 : Acrobatie Nv1                                  Dextérité                  Dx-2",
			"02 : Acrobatie Nv2                                  Dextérité                  Dx-1",
			"04 : Acrobatie Nv3                                  Dextérité                  Dx",
			"08 : Acrobatie Nv4                                  Dextérité	                 Dx+1",
			"12 : Acrobatie Nv5                                  Dextérité                  Dx+2",
			"16 : Acrobatie Nv6                                  Dextérité                  Dx+3",
			"01 : Armes de jet Nv1                               Dextérité	                 Dx",
			"02 : Armes de jet Nv2                               Dextérité	                 Dx+1",
			"04 : Armes de jet Nv3                               Dextérité	                 Dx+2",
			"08 : Armes de jet Nv4                               Dextérité	                 Dx+3",
			"01 : Hache/Masse Nv1                                Dextérité	                 Dx-1",
			"02 : Hache/Masse Nv2                                Dextérité	                 Dx",
			"04 : Hache/Masse Nv3                                Dextérité	                 Dx+1",
			"08 : Hache/Masse Nv4                                Dextérité	                 Dx+2",
			"12 : Hache/Masse Nv5                                Dextérité	                 Dx+3",
			"01 : Rapière/Fleuret Nv1                            Dextérité	                 Dx-1",
			"02 : Rapière/Fleuret Nv2                            Dextérité	                 Dx",
			"04 : Rapière/Fleuret Nv3                            Dextérité	                 Dx+1",
			"08 : Rapière/Fleuret Nv4                            Dextérité	                 Dx+2",
			"12 : Rapière/Fleuret Nv5                            Dextérité	                 Dx+3",
			"01 : Hallebarde/Epieux Nv1                          Dextérité	                 Dx-1",
			"02 : Hallebarde/Epieux Nv2                          Dextérité	                 Dx",
			"04 : Hallebarde/Epieux Nv3                          Dextérité	                 Dx+1",
			"08 : Hallebarde/Epieux Nv4                          Dextérité	                 Dx+2",
			"12 : Hallebarde/Epieux Nv5                          Dextérité	                 Dx+3",
			"01 : Epées Nv1                                      Dextérité	                 Dx-1",
			"02 : Epées Nv2                                      Dextérité	                 Dx",
			"04 : Epées Nv3                                      Dextérité	                 Dx+1",
			"08 : Epées Nv4                                      Dextérité	                 Dx+2",
			"12 : Epées Nv5                                      Dextérité	                 Dx+3",
			"01 : Fléaux/Nunchakus Nv1                           Dextérité	                 Dx-2",
			"02 : Fléaux/Nunchakus Nv2                           Dextérité	                 Dx-1",
			"04 : Fléaux/Nunchakus Nv3                           Dextérité	                 Dx",
			"08 : Fléaux/Nunchakus Nv4                           Dextérité	                 Dx+1",
			"12 : Fléaux/Nunchakus Nv5                           Dextérité	                 Dx+2",
			"16 : Fléaux/Nunchakus Nv6                           Dextérité	                 Dx+3",
			"01 : Arbalètes Nv1                                  Dextérité	                 Dx",
			"02 : Arbalètes Nv2                                  Dextérité	                 Dx+1",
			"04 : Arbalètes Nv3                                  Dextérité	                 Dx+2",
			"08 : Arbalètes Nv4                                  Dextérité	                 Dx+3",
			"01 : Arc Nv1                                        Dextérité	                 Dx-1",
			"02 : Arc Nv2                                        Dextérité	                 Dx",
			"04 : Arc Nv3                                        Dextérité	                 Dx+1",
			"08 : Arc Nv4                                        Dextérité	                 Dx+2",
			"12 : Arc Nv5                                        Dextérité	                 Dx+3",
			"01 : Armes à poudre Nv1                             Dextérité	                 Dx",
			"02 : Armes à poudre Nv2                             Dextérité	                 Dx+1",
			"04 : Armes à poudre Nv3                             Dextérité	                 Dx+2",
			"08 : Armes à poudre Nv4                             Dextérité	                 Dx+3",
			"01 : Frondes/Lance pierre/Sarbacane Nv1             Dextérité	                 Dx-2",
			"02 : Frondes/Lance pierre/Sarbacane Nv2             Dextérité	                 Dx-1",
			"04 : Frondes/Lance pierre/Sarbacane Nv3             Dextérité	                 Dx",
			"08 : Frondes/Lance pierre/Sarbacane Nv4             Dextérité	                 Dx+1",
			"12 : Frondes/Lance pierre/Sarbacane Nv5             Dextérité	                 Dx+2",
			"16 : Frondes/Lance pierre/Sarbacane Nv6             Dextérité	                 Dx+3",
			"01 : Armurerie Nv1                                  QI                         Qi-1",
			"02 : Armurerie Nv2                       			  QI                         Qi",
			"04 : Armurerie Nv3                       			  QI             		     Qi+1",
			"08 : Armurerie Nv4                      			  QI              		     Qi+2",
			"12 : Armurerie Nv5                     			  QI             	         Qi+3",
			"01 : Arts martiaux Nv1        				      Dextérité                  Dx-2",
			"02 : Arts martiaux Nv2        				      Dextérité                  Dx-1",
			"04 : Arts martiaux Nv3        				      Dextérité                  Dx",
			"08 : Arts martiaux Nv4        				      Dextérité                  Dx+1",
			"12 : Arts martiaux Nv5        				      Dextérité                  Dx+2",
			"16 : Arts martiaux Nv6        				      Dextérité                  Dx+3",
			"01 : Bagarre Nv1                   		          Dextérité                  Dx",
			"02 : Bagarre Nv2                     		          Dextérité                  Dx+1",
			"04 : Bagarre Nv3                    		          Dextérité                  Dx+2",
			"08 : Bagarre Nv4                     		          Dextérité                  Dx+3",
			"01 : Beaux-arts Nv1        				          QI                         Qi-2",
			"02 : Beaux-arts Nv2        				          QI                         Qi-1",
			"04 : Beaux-arts Nv3        				          QI                         Qi",
			"08 : Beaux-arts Nv4        				          QI                         Qi+1",
			"12 : Beaux-arts Nv5        				          QI                         Qi+2",
			"16 : Beaux-arts Nv6        				          QI                         Qi+3",
			"01 : Bibliothèque Nv1                               QI                         Qi-1",
			"02 : Bibliothèque Nv2                      		  QI                         Qi",
			"04 : Bibliothèque Nv3                       		  QI             		     Qi+1",
			"08 : Bibliothèque Nv4                      		  QI              		     Qi+2",
			"12 : Bibliothèque Nv5                     		  QI             	         Qi+3",
			"01 : Bouclier Nv1                   		          Dextérité                  Dx",
			"02 : Bouclier Nv2                     		      Dextérité                  Dx+1",
			"04 : Bouclier Nv3                    		          Dextérité                  Dx+2",
			"08 : Bouclier Nv4                     		      Dextérité                  Dx+3",
			"01 : Chant Nv1                                      Santé                      Sa",
			"02 : Chant Nv2                      		          Santé                      Sa+1",
			"04 : Chant Nv3                       		  		  Santé           		     Sa+2",
			"08 : Chant Nv4                      		          Santé              		 Sa+3",
			"01 : Chirurgie Nv1        				          QI                         Qi-2",
			"02 : Chirurgie Nv2        				          QI                         Qi-1",
			"04 : Chirurgie Nv3        				          QI                         Qi",
			"08 : Chirurgie Nv4        				          QI                         Qi+1",
			"12 : Chirurgie Nv5        				          QI                         Qi+2",
			"16 : Chirurgie Nv6        				          QI                         Qi+3",
			"01 : Comédie Nv1                            	      QI                         Qi-1",
			"02 : Comédie Nv2                      			  QI                         Qi",
			"04 : Comédie Nv3                       			  QI             		     Qi+1",
			"08 : Comédie Nv4                      			  QI              		     Qi+2",
			"12 : Comédie Nv5                     		  		  QI             	         Qi+3",
			"01 : Commandement Nv1                               QI                         Qi-1",
			"02 : Commandement Nv2                      		  QI                         Qi",
			"04 : Commandement Nv3                       		  QI             		     Qi+1",
			"08 : Commandement Nv4                      		  QI              		     Qi+2",
			"12 : Commandement Nv5                     		  QI             	         Qi+3",
			"01 : Commerce Nv1                         	      QI                         Qi-1",
			"02 : Commerce Nv2                      			  QI                         Qi",
			"04 : Commerce Nv3                       			  QI             		     Qi+1",
			"08 : Commerce Nv4                      			  QI              		     Qi+2",
			"12 : Commerce Nv5                     			  QI             	         Qi+3",
			"01 : Diplomatie Nv1        				          QI                         Qi-2",
			"02 : Diplomatie Nv2        				          QI                         Qi-1",
			"04 : Diplomatie Nv3        				          QI                         Qi",
			"08 : Diplomatie Nv4        				          QI                         Qi+1",
			"12 : Diplomatie Nv5        				          QI                         Qi+2",
			"16 : Diplomatie Nv6        				          QI                         Qi+3",
			"01 : Baratin Nv1                      	   	      QI                         Qi-1",
			"02 : Baratin Nv2                      			  QI                         Qi",
			"04 : Baratin Nv3                       			  QI             		     Qi+1",
			"08 : Baratin Nv4                      			  QI              		     Qi+2",
			"12 : Baratin Nv5                    	 			  QI             	         Qi+3",
			"01 : Intimidation Nv1                   	   	      QI                         Qi-1",
			"02 : Intimidation Nv2                    			  QI                         Qi",
			"04 : Intimidation Nv3                    			  QI             		     Qi+1",
			"08 : Intimidation Nv4                     		  QI              		     Qi+2",
			"12 : Intimidation Nv5                    	 		  QI             	         Qi+3",
			"01 : Etiquette Nv1             	      	   	      QI                         Qi",
			"02 : Etiquette Nv2                    			  QI                         Qi+1",
			"04 : Etiquette Nv3                    			  QI             		     Qi+2",
			"08 : Etiquette Nv4              		       		  QI              		     Qi+3",
			"01 : Séduction Nv1                                  Santé                      Sa-1",
			"02 : Séduction Nv2                      		      Santé                      Sa",
			"04 : Séduction Nv3                       		  	  Santé           		     Sa+1",
			"08 : Séduction Nv4                      		      Santé              		 Sa+2",
			"12 : Séduction Nv5                      		      Santé              		 Sa+3",
			"01 : Connaissance de la rue Nv1                     QI                         Qi-1",
			"02 : Connaissance de la rue Nv2                     QI                         Qi",
			"04 : Connaissance de la rue Nv3                 	  QI             		     Qi+1",
			"08 : Connaissance de la rue Nv4                     QI              		     Qi+2",
			"12 : Connaissance de la rue Nv5                     QI             	         Qi+3",
			"01 : Conduite :           Nv1                   	  Dextérité                  Dx",
			"02 : Conduite :           Nv2             	      Dextérité                  Dx+1",
			"04 : Conduite :           Nv3                       Dextérité                  Dx+2",
			"08 : Conduite :           Nv4             	      Dextérité                  Dx+3",
			"01 : Connaissance de la nature Nv1        		  QI                         Qi-2",
			"02 : Connaissance de la nature Nv2        		  QI                         Qi-1",
			"04 : Connaissance de la nature Nv3        		  QI                         Qi",
			"08 : Connaissance de la nature Nv4        		  QI                         Qi+1",
			"12 : Connaissance de la nature Nv5        		  QI                         Qi+2",
			"16 : Connaissance de la nature Nv6        		  QI                         Qi+3",
			"01 : Contrefaçon Nv1        						  QI                         Qi-2",
			"02 : Contrefaçon Nv2        						  QI                         Qi-1",
			"04 : Contrefaçon Nv3        						  QI                         Qi",
			"08 : Contrefaçon Nv4        						  QI                         Qi+1",
			"12 : Contrefaçon Nv5        						  QI                         Qi+2",
			"16 : Contrefaçon Nv6        						  QI                         Qi+3",
			"01 : Criminalistique Nv1        					  QI                         Qi-2",
			"02 : Criminalistique Nv2        					  QI                         Qi-1",
			"04 : Criminalistique Nv3        					  QI                         Qi",
			"08 : Criminalistique Nv4        					  QI                         Qi+1",
			"12 : Criminalistique Nv5        					  QI                         Qi+2",
			"16 : Criminalistique Nv6        					  QI                         Qi+3",
			"01 : Criminologie Nv1                  		      QI                         Qi-1",
			"02 : Criminologie Nv2               			      QI                         Qi",
			"04 : Criminologie Nv3                			 	  QI             		     Qi+1",
			"08 : Criminologie Nv4                			      QI              		     Qi+2",
			"12 : Criminologie Nv5                			      QI             	         Qi+3",
			"01 : Crochetage Nv1                  			      QI                         Qi-1",
			"02 : Crochetage Nv2               			      QI                         Qi",
			"04 : Crochetage Nv3                			 	  QI             		     Qi+1",
			"08 : Crochetage Nv4                			      QI              		     Qi+2",
			"12 : Crochetage Nv5                			      QI             	         Qi+3",
			"01 : Cuisine Nv1             	      	   		      QI                         Qi",
			"02 : Cuisine Nv2                    				  QI                         Qi+1",
			"04 : Cuisine Nv3                    				  QI             		     Qi+2",
			"08 : Cuisine Nv4              		       		  QI              		     Qi+3",
			"01 : Danse Nv1                                      Dextérité                  Dx-1",
			"02 : Danse Nv2                                      Dextérité                  Dx",
			"04 : Danse Nv3                                      Dextérité                  Dx+1",
			"08 : Danse Nv4                                      Dextérité                  Dx+2",
			"12 : Danse Nv5                                      Dextérité                  Dx+3",
			"01 : Déguisement Nv1                  			  QI                         Qi-1",
			"02 : Déguisement Nv2               			      QI                         Qi",
			"04 : Déguisement Nv3                			 	  QI             		     Qi+1",
			"08 : Déguisement Nv4                			      QI              		     Qi+2",
			"12 : Déguisement Nv5                			      QI             	         Qi+3",
			"01 : Diagnostique Nv1        						  QI                         Qi-2",
			"02 : Diagnostique Nv2        						  QI                         Qi-1",
			"04 : Diagnostique Nv3        						  QI                         Qi",
			"08 : Diagnostique Nv4        						  QI                         Qi+1",
			"12 : Diagnostique Nv5        						  QI                         Qi+2",
			"16 : Diagnostique Nv6        						  QI                         Qi+3",
			"01 : Discrétion Nv1                  				  QI                         Qi-1",
			"02 : Discrétion Nv2               			      QI                         Qi",
			"04 : Discrétion Nv3                			 	  QI             		     Qi+1",
			"08 : Discrétion Nv4                			      QI              		     Qi+2",
			"12 : Discrétion Nv5                			      QI             	         Qi+3",
			"01 : Dissimulation Nv1                  			  QI                         Qi-1",
			"02 : Dissimulation Nv2               			      QI                         Qi",
			"04 : Dissimulation Nv3                			  QI             		     Qi+1",
			"08 : Dissimulation Nv4                			  QI              		     Qi+2",
			"12 : Dissimulation Nv5                			  QI             	         Qi+3",
			"01 : Dréssage Nv1        							  QI                         Qi-2",
			"02 : Dréssage Nv2        							  QI                         Qi-1",
			"04 : Dréssage Nv3        							  QI                         Qi",
			"08 : Dréssage Nv4        							  QI                         Qi+1",
			"12 : Dréssage Nv5        							  QI                         Qi+2",
			"16 : Dréssage Nv6        							  QI                         Qi+3",
			"01 : Droit Nv1        							  QI                         Qi-2",
			"02 : Droit Nv2        							  QI                         Qi-1",
			"04 : Droit Nv3        							  QI                         Qi",
			"08 : Droit Nv4        							  QI                         Qi+1",
			"12 : Droit Nv5        							  QI                         Qi+2",
			"16 : Droit Nv6        							  QI                         Qi+3",
			"01 : Ecriture Nv1                		  			  QI                         Qi-1",
			"02 : Ecriture Nv2               				      QI                         Qi",
			"04 : Ecriture Nv3                					  QI             		     Qi+1",
			"08 : Ecriture Nv4                					  QI              		     Qi+2",
			"12 : Ecriture Nv5                					  QI             	         Qi+3",
			"01 : Eloquence Nv1                		  		  QI                         Qi-1",
			"02 : Eloquence Nv2               				      QI                         Qi",
			"04 : Eloquence Nv3                				  QI             		     Qi+1",
			"08 : Eloquence Nv4                				  QI              		     Qi+2",
			"12 : Eloquence Nv5                				  QI             	         Qi+3",
			"01 : Enseignement Nv1                		  		  QI                         Qi-1",
			"02 : Enseignement Nv2               				  QI                         Qi",
			"04 : Enseignement Nv3                				  QI             		     Qi+1",
			"08 : Enseignement Nv4                				  QI              		     Qi+2",
			"12 : Enseignement Nv5                				  QI             	         Qi+3",
			"01 : Equitation Nv1                		  		  Dextérité                  Dx-1",
			"02 : Equitation Nv2               				  Dextérité                  Dx",
			"04 : Equitation Nv3                				  Dextérité             	 Dx+1",
			"08 : Equitation Nv4                				  Dextérité              	 Dx+2",
			"12 : Equitation Nv5                				  Dextérité             	 Dx+3",
			"01 : Escalade Nv1         	       		  		  Dextérité                  Dx-1",
			"02 : Escalade Nv2         	      				  Dextérité                  Dx",
			"04 : Escalade Nv3         	       				  Dextérité             	 Dx+1",
			"08 : Escalade Nv4         	       				  Dextérité              	 Dx+2",
			"12 : Escalade Nv5         	       				  Dextérité             	 Dx+3",
			"01 : Evasion Nv1        						      Dextérité                  Dx-2",
			"02 : Evasion Nv2        						      Dextérité                  Dx-1",
			"04 : Evasion Nv3        						      Dextérité                  Dx",
			"08 : Evasion Nv4        						      Dextérité                  Dx+1",
			"12 : Evasion Nv5        						      Dextérité                  Dx+2",
			"16 : Evasion Nv6        						      Dextérité                  Dx+3",
			"01 : Explosif Nv1              	  		  		  QI                         Qi-1",
			"02 : Explosif Nv2              	 				  QI                         Qi",
			"04 : Explosif Nv3               	 				  QI             		     Qi+1",
			"08 : Explosif Nv4               	 				  QI              		     Qi+2",
			"12 : Explosif Nv5               	 				  QI             	         Qi+3",
			"01 : Filature Nv1              	  		  		  QI                         Qi-1",
			"02 : Filature Nv2              	 				  QI                         Qi",
			"04 : Filature Nv3               	 				  QI             		     Qi+1",
			"08 : Filature Nv4               	 				  QI              		     Qi+2",
			"12 : Filature Nv5               	 				  QI             	         Qi+3",
			"01 : Fouille Nv1              	  		  		  QI                         Qi-1",
			"02 : Fouille Nv2              	 				  QI                         Qi",
			"04 : Fouille Nv3               	 				  QI             		     Qi+1",
			"08 : Fouille Nv4               	 				  QI              		     Qi+2",
			"12 : Fouille Nv5               	 				  QI             	         Qi+3",
			"01 : Géographie locale Nv1             	          QI                         Qi",
			"02 : Géographie locale Nv2                    	  QI                         Qi+1",
			"04 : Géographie locale Nv3                    	  QI             		     Qi+2",
			"08 : Géographie locale Nv4              		      QI              		     Qi+3",
			"01 : Humanités Nv1        						  QI                         Qi-2",
			"02 : Humanités Nv2        						  QI                         Qi-1",
			"04 : Humanités Nv3        						  QI                         Qi",
			"08 : Humanités Nv4        						  QI                         Qi+1",
			"12 : Humanités Nv5        						  QI                         Qi+2",
			"16 : Humanités Nv6        						  QI                         Qi+3",
			"01 : Informatique Nv1             	        	  QI                         Qi",
			"02 : Informatique Nv2                    	 		  QI                         Qi+1",
			"04 : Informatique Nv3                    	 		  QI             		     Qi+2",
			"08 : Informatique Nv4              			      QI              		     Qi+3",
			"01 : Ingénierie Nv1        						  QI                         Qi-2",
			"02 : Ingénierie Nv2        						  QI                         Qi-1",
			"04 : Ingénierie Nv3        						  QI                         Qi",
			"08 : Ingénierie Nv4        						  QI                         Qi+1",
			"12 : Ingénierie Nv5        						  QI                         Qi+2",
			"16 : Ingénierie Nv6        						  QI                         Qi+3",
			"01 : Instrument de musique Nv1        			  QI                         Qi-2",
			"02 : Instrument de musique Nv2        			  QI                         Qi-1",
			"04 : Instrument de musique Nv3        			  QI                         Qi",
			"08 : Instrument de musique Nv4        			  QI                         Qi+1",
			"12 : Instrument de musique Nv5        			  QI                         Qi+2",
			"16 : Instrument de musique Nv6        			  QI                         Qi+3",
			"01 : Interrogatoire Nv1              	  		  	  QI                         Qi-1",
			"02 : Interrogatoire Nv2              	 			  QI                         Qi",
			"04 : Interrogatoire Nv3               	 		  QI             		     Qi+1",
			"08 : Interrogatoire Nv4               	 		  QI              		     Qi+2",
			"12 : Interrogatoire Nv5               	 		  QI             	         Qi+3",
			"01 : Jeu Nv1              			  		  	  QI                         Qi-1",
			"02 : Jeu Nv2              			 			  QI                         Qi",
			"04 : Jeu Nv3               				 		  QI             		     Qi+1",
			"08 : Jeu Nv4               				 		  QI              		     Qi+2",
			"12 : Jeu Nv5               				 		  QI             	         Qi+3",
			"01 : Lancer Nv1         		       		  		  Dextérité                  Dx-1",
			"02 : Lancer Nv2         		      				  Dextérité                  Dx",
			"04 : Lancer Nv3        	 	       				  Dextérité             	 Dx+1",
			"08 : Lancer Nv4       	  	       				  Dextérité              	 Dx+2",
			"12 : Lancer Nv5       	  	       				  Dextérité             	 Dx+3",
			"01 : Mécanique Nv1              			  	  	  QI                         Qi-1",
			"02 : Mécanique Nv2              			 		  QI                         Qi",
			"04 : Mécanique Nv3               					  QI             		     Qi+1",
			"08 : Mécanique Nv4               					  QI              		     Qi+2",
			"12 : Mécanique Nv5               					  QI             	         Qi+3",
			"01 : Médecine Nv1        							  QI                         Qi-2",
			"02 : Médecine Nv2        							  QI                         Qi-1",
			"04 : Médecine Nv3        							  QI                         Qi",
			"08 : Médecine Nv4        							  QI                         Qi+1",
			"12 : Médecine Nv5        							  QI                         Qi+2",
			"16 : Médecine Nv6        							  QI                         Qi+3",
			"01 : Météorologie Nv1              			   	  QI                         Qi-1",
			"02 : Météorologie Nv2              				  QI                         Qi",
			"04 : Météorologie Nv3               				  QI             		     Qi+1",
			"08 : Météorologie Nv4               				  QI              		     Qi+2",
			"12 : Météorologie Nv5               				  QI             	         Qi+3",
			"01 : Natation Nv1                                   Santé                      Sa",
			"02 : Natation Nv2                      		      Santé                      Sa+1",
			"04 : Natation Nv3                       		  	  Santé           		     Sa+2",
			"08 : Natation Nv4                      		      Santé              		 Sa+3",
			"01 : Navigation Nv1        						  QI                         Qi-2",
			"02 : Navigation Nv2        						  QI                         Qi-1",
			"04 : Navigation Nv3        						  QI                         Qi",
			"08 : Navigation Nv4        						  QI                         Qi+1",
			"12 : Navigation Nv5        						  QI                         Qi+2",
			"16 : Navigation Nv6        						  QI                         Qi+3",
			"01 : Occultisme Nv1              				   	  QI                         Qi-1",
			"02 : Occultisme Nv2              					  QI                         Qi",
			"04 : Occultisme Nv3               				  QI             		     Qi+1",
			"08 : Occultisme Nv4               				  QI              		     Qi+2",
			"12 : Occultisme Nv5               				  QI             	         Qi+3",
			"01 : Photographie Nv1              			   	  QI                         Qi-1",
			"02 : Photographie Nv2              				  QI                         Qi",
			"04 : Photographie Nv3               				  QI             		     Qi+1",
			"08 : Photographie Nv4               				  QI              		     Qi+2",
			"12 : Photographie Nv5               				  QI             	         Qi+3",
			"01 : Pickpocket Nv1        					      Dextérité                  Dx-2",
			"02 : Pickpocket Nv2        					      Dextérité                  Dx-1",
			"04 : Pickpocket Nv3        					      Dextérité                  Dx",
			"08 : Pickpocket Nv4        					      Dextérité                  Dx+1",
			"12 : Pickpocket Nv5        					      Dextérité                  Dx+2",
			"16 : Pickpocket Nv6        					      Dextérité                  Dx+3",
			"01 : Piégeage Nv1         	     			   	  QI                         Qi-1",
			"02 : Piégeage Nv2          	    				  QI                         Qi",
			"04 : Piégeage Nv3          	     				  QI             		     Qi+1",
			"08 : Piégeage Nv4          	     				  QI              		     Qi+2",
			"12 : Piégeage Nv5          	     				  QI             	         Qi+3",
			"01 : Pistage Nv1         	     				   	  QI                         Qi-1",
			"02 : Pistage Nv2          	    				  QI                         Qi",
			"04 : Pistage Nv3          	     				  QI             		     Qi+1",
			"08 : Pistage Nv4          	     				  QI              		     Qi+2",
			"12 : Pistage Nv5          	     				  QI             	         Qi+3",
			"01 : Politique Nv1         	     				  QI                         Qi-1",
			"02 : Politique Nv2          	    				  QI                         Qi",
			"04 : Politique Nv3          	     				  QI             		     Qi+1",
			"08 : Politique Nv4          	     				  QI              		     Qi+2",
			"12 : Politique Nv5          	     				  QI             	         Qi+3",
			"01 : Premiers soins Nv1             	 	          QI                         Qi",
			"02 : Premiers soins Nv2                	    	  QI                         Qi+1",
			"04 : Premiers soins Nv3                  		  	  QI             		     Qi+2",
			"08 : Premiers soins Nv4              		 	      QI              		     Qi+3",
			"01 : Programation Nv1        						  QI                         Qi-2",
			"02 : Programation Nv2        						  QI                         Qi-1",
			"04 : Programation Nv3        						  QI                         Qi",
			"08 : Programation Nv4        						  QI                         Qi+1",
			"12 : Programation Nv5        						  QI                         Qi+2",
			"16 : Programation Nv6        						  QI                         Qi+3",
			"01 : Saut Nv1         		       		  		  Dextérité                  Dx",
			"02 : Saut Nv2         		      				  Dextérité                  Dx+1",
			"04 : Saut Nv3        	 		       				  Dextérité             	 Dx+2",
			"08 : Saut Nv4       	  		       				  Dextérité              	 Dx+3",
			"01 : Sciences de la nature Nv1        			  QI                         Qi-2",
			"02 : Sciences de la nature Nv2        			  QI                         Qi-1",
			"04 : Sciences de la nature Nv3        			  QI                         Qi",
			"08 : Sciences de la nature Nv4        			  QI                         Qi+1",
			"12 : Sciences de la nature Nv5        			  QI                         Qi+2",
			"16 : Sciences de la nature Nv6        			  QI                         Qi+3",
			"01 : Sciences sociales Nv1        				  QI                         Qi-2",
			"02 : Sciences sociales Nv2        				  QI                         Qi-1",
			"04 : Sciences sociales Nv3        				  QI                         Qi",
			"08 : Sciences sociales Nv4        				  QI                         Qi+1",
			"12 : Sciences sociales Nv5        				  QI                         Qi+2",
			"16 : Sciences sociales Nv6        				  QI                         Qi+3",
			"01 : Survie Nv1         	     					  QI                         Qi-1",
			"02 : Survie Nv2          	    					  QI                         Qi",
			"04 : Survie Nv3          	     					  QI             		     Qi+1",
			"08 : Survie Nv4          	     					  QI              		     Qi+2",
			"12 : Survie Nv5          	     					  QI             	         Qi+3",
			"01 : Tactique Nv1        							  QI                         Qi-2",
			"02 : Tactique Nv2        							  QI                         Qi-1",
			"04 : Tactique Nv3        							  QI                         Qi",
			"08 : Tactique Nv4        							  QI                         Qi+1",
			"12 : Tactique Nv5        				  			  QI                         Qi+2",
			"16 : Tactique Nv6        							  QI                         Qi+3",
			"01 : Tétologie Nv1        			   		      QI                         Qi-2",
			"02 : Tétologie Nv2        					      QI                         Qi-1",
			"04 : Tétologie Nv3        					      QI                         Qi",
			"08 : Tétologie Nv4        					      QI                         Qi+1",
			"12 : Tétologie Nv5        			 		      QI                         Qi+2",
			"16 : Tétologie Nv6        			 		      QI                         Qi+3",
			"01 : Thaumatologie Nv1        					  QI                         Qi-2",
			"02 : Thaumatologie Nv2        					  QI                         Qi-1",
			"04 : Thaumatologie Nv3        					  QI                         Qi",
			"08 : Thaumatologie Nv4        					  QI                         Qi+1",
			"12 : Thaumatologie Nv5        			 		  QI                         Qi+2",
			"16 : Thaumatologie Nv6        					  QI                         Qi+3",
			"01 : Langage des signes Nv1         	     		  QI                         Qi-1",
			"02 : Langage des signes Nv2          	    		  QI                         Qi",
			"04 : Langage des signes Nv3          	    		  QI             		     Qi+1",
			"08 : Langage des signes Nv4          	    		  QI              		     Qi+2",
			"12 : Langage des signes Nv5          	    		  QI             	         Qi+3",
			"01 : Pantomine Nv1             	 	    	      QI                         Qi",
			"02 : Pantomine Nv2                	  		  	  QI                         Qi+1",
			"04 : Pantomine Nv3                  			  	  QI             		     Qi+2",
			"08 : Pantomine Nv4              		 		      QI              		     Qi+3", };

	String choixLangues[] = { "10 : Morporkien", "10 : Langrien", "10 : Agateen", "10 : Klachien", "10 : Nain",
			"10 : Troll", "10 : Gobelin", "15 : Nac Mac Feegles", "10 : Xixixixien", "10 : Krullien",
			"10 : Uberwaldien", "10 : Ephebien", "10 : Tsorien" };

	String[] choixPoint = { "25 pts : faible(Zombies, Petit enfants...)", "50 pts : moyen(gens normaux)",
			"75 pts : compétents(Policiers, Athlètes, Nobles...", "100 pts : Exceptionelle(Vétérans, Dirigeants...)",
			"200 pts : Heros(Genies, Millionnaires, Guerriers d'�lites..)",
			"300 pts : Légende(Héros barbares, Dieux)" };

	String[] choixMetier = { "Aucun", "Acteur", "Agent du guet", "Alchimistes", "Assassin", "Avocat", "Boulanger",
			"Commerçant", "Contrebandier", "Couturière", "Diplomate", "Fermier", "Fou", "Jardinier", "Journaliste",
			"Mage", "Majordome", "Mendiant", "Militaire", "Mime des rues", "Mineur", "Musicien", "Ouvrier", "Prêtre",
			"Sorcière", "Usurier", "Voleur" };

	String[] choixNat = { "Ankh-Morpork", "Quirm", "Le Village paumé, là-bas", "Langre", "Ephèbe", "Klach", "Agateen",
			"Iksiksiksiks", "Krull", "Gilnéas", "Uberwald", "Omnia", "Jolhimôme", "Pseudopolis" };

	String[] choixRace = { "Humain", "Nain", "Troll", "Gobelin", "Nac Mac Feegle", "Mort-vivant", "Vampire",
			"Loup-garou", "Zombie", "Gnome", "Igor" };

	String[] choixApparence = { "-16 : Monstrueux comme un igor", "-08 : Laid comme un gobelin",
			"-04 : Peu Attirant comme un nain", "00 : Moyen, banal comme la plupart des gens",
			"+04 : Séduisant comme une couturière", "+12 : Beau comme un éphèbe", "+16 : Superbe comme un dieux" };

	String[] choixMagie = { "01 : Abrutissement : retire X pts de QI pour X PdF utilisées.",
			"01 : Allumer un feu : X PdF selon la chaleur nécessaire.",
			"01 : Bénédiction : bonus de X au jet pour X Pdf utilisées, 3PdF Max.",
			"01 : Blocage : X bonus de défense pour X Pdf utilisées, 3PdF Max.",
			"01 : Bouclier : 2X bonus de défense pour X Pdf utilisées.",
			"01 : Boule de feu : XD de dommages pour X PdF utilisées, 3 PdF max.",
			"01 : Boule de Glace : XD de dommages pour X PdF utilisées, 3 PdF max.",
			"01 : Créer un feu : Allumer un feu sans combustible. 2 PdF.",
			"01 : Déplacement : déplacer un objet, cout en fonction du poids.",
			"01 : Refroidissement : Reffroidi la cible de 10°/1 PdF ", "01 : Détection de la magie : 2 Pdf.",
			"01 : Don de santé : rend X PdV à la cible pour X PdV et PdF utilisées.",
			"01 : Don de Force : rend X PdF à la cible pour X PdF utilisées.", "01 : Ecarter un projectile : 1 PdF",
			"01 : Enchanter : Enchantement divers, 0 à 10 PdF en fonction de l'effet",
			"01 : Façonner un feu : Déplacer oun modifier la forme d'un feu. 2 PdF.",
			"01 : Hâte : +X en mouvement et esquive pas PdF utilisées. 3 max.",
			"01 : Hypnose : La cible est confuse. 3 PdF.",
			"01 : Invoquer un démon : 10 Pdf + jet de vol pour controle du démon.",
			"01 : Lumière : Produit unepetite lumier pendant 1 minute. 1 PdF.",
			"01 : Malédiction : malus de X au jet pour X Pdf utilisées, 3PdF Max.",
			"01 : Sommeil : la cible s'endort pour les 8 prochaines heures. 4 PdF.",
			"01 : Rétroaction mystique : contrer l'envoutement lancé sur soi. 4 PdF.",
			"01 : Octogramme : Créer une barrière de protection magique. 10 Pdf/m².",
			"01 : Exploiter le pouvoir de la narration : voir livre de régle. 2 PdF.",
			"01 : Exhausteur d'Englebert : voir livre de rêgle P132. 1 PdF.",
			"01 : Emprunt : projette son esprit dans la cible. Coût variable.",
			"01 : Altération morphique : Change l'App de la cible. Coût variable.",
			"01 : Divination : voir livre de rêgle P136. coût variable.",
			"01 : Surprise incendiaire de Sautepuisard : allume un feu Sp. 3 PdF.",
			"01 : Enchantement : Comme divination, mais avec un boule de cristal.",
			"01 : Téléportaion : Le lanceur se téléporte. Coût PdF/Distance.",
			"01 : Chamboule-tout gravitationel d'Atavar : voir livre de rêgle P141.",
			"01 : Point d'attraction de Quondum : voir livre de rêgle P141.",
			"01 : Manipulation narrative : voir livre de rêgle P140.",
			"01 : Briser les barrières mentales : voir livre de rêgle P139.",
			"01 : Suspendre le temps : arrête le temps temporairement. 20 PdF.",
			"01 : Le rite d'AshkEnte : Invoque la mort. 5 PdF et un oeuf.",
			"01 : Attraper les blessures : Voir livre de rêgle P146.",
			"01 : Respirateur Spontané de Spolt : force la cible à respirer. 3 PdF.",
			"01 : Bouquet susprise d'Erineygas : Créer un bouquet de fleurs. 1 PdF.",
			"01 : Merveilleux concentrateur de Fresnel : voir livre de rêgle P146.",
			"01 : Invoquer un diablotin : invoque un diablotin, coût variable.",
			"01 : Envoûtement : Envoûte la cible. Coût variable.",
			"01 : Délire : Implante un délire dans l'esprit de la cible. 5 PdF.",
			"01 : Hibernation de masse : voir livre de rêgle P 139."

	};

}

// https://fr.wikipedia.org/wiki/Lieux_du_Disque-monde
